In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("affordance_natural.csv")
df = df[df['prompt_type'] == "implicit"]
df.head(3)

,group_id,condition,prompt_type,key_verb,afforded_text,non-afforded_text,related_text,afforded_image,non-afforded_image,related_image
18,1,Brad was sitting in his office when an intrude...,implicit,protect,laptop computer,paper napkin,hunting rifle,laptopcomputer_natural.jpeg,papernapkin_natural.jpeg,huntingrifle_natural.jpeg
19,2,Jenny was hiking in the woods. She left her fr...,implicit,point,pen,nickel,string,pen_natural.jpeg,nickel_natural.jpeg,string_natural.jpeg
20,3,Art was having a party. He realized he didn't ...,implicit,protect,floppy disks,pencils,old magazines,floppydisks_natural.jpeg,pencils_natural.jpeg,oldmagazines_natural.jpeg

In [3]:
df['scenario'] = df['condition']

In [4]:
conditions = ['afforded', 'non-afforded', 'related']

# We'll collect rows in a list of dicts, then convert to DataFrame
output_rows = []

# Enumerate each row in the original CSV
for i, row in df.iterrows():
    # i = row index (0-based)
    # row = the actual row data (scenario, afforded_image, ...)

    scenario_id = row['condition'] 

    # For each group (1..3), we rotate conditions in a Latin Square manner
    for group in range(3):
        # condition index: shift by (i + group)
        condition_idx = (i + group) % 3
        condition_name = conditions[condition_idx]

        # figure out which image column to pull
        # e.g., for 'afforded', we look at row['afforded_image']
        if condition_name == 'afforded':
            image_path = row['afforded_image']
        elif condition_name == 'non-afforded':
            image_path = row['non-afforded_image']
        else:
            image_path = row['related_image']

        image_path = "images/" + image_path

        output_rows.append({
            'list_id'  : group + 1,        # groups labeled 1, 2, 3
            'scenario'  : scenario_id,
            'condition' : condition_name.title(),
            'group_id': row['group_id'],
            'image_path': image_path,
            
        })

# Create a new DataFrame
latin_df = pd.DataFrame(output_rows)

In [5]:
latin_df.groupby("list_id")['condition'].value_counts()

list_id  condition
1        Afforded        6
         Non-Afforded    6
         Related         6
2        Afforded        6
         Non-Afforded    6
         Related         6
3        Afforded        6
         Non-Afforded    6
         Related         6
Name: count, dtype: int64

In [6]:
latin_df.head(2)

,list_id,scenario,condition,group_id,image_path
0,1,Brad was sitting in his office when an intrude...,Afforded,1,images/laptopcomputer_natural.jpeg
1,2,Brad was sitting in his office when an intrude...,Non-Afforded,1,images/papernapkin_natural.jpeg

In [13]:
latin_df

,list_id,scenario,condition,group_id,image_path
0,1,Brad was sitting in his office when an intrude...,Afforded,1,images/laptopcomputer_natural.jpeg
1,2,Brad was sitting in his office when an intrude...,Non-Afforded,1,images/papernapkin_natural.jpeg
2,3,Brad was sitting in his office when an intrude...,Related,1,images/huntingrifle_natural.jpeg
3,1,Jenny was hiking in the woods. She left her fr...,Non-Afforded,2,images/nickel_natural.jpeg
4,2,Jenny was hiking in the woods. She left her fr...,Related,2,images/string_natural.jpeg
5,3,Jenny was hiking in the woods. She left her fr...,Afforded,2,images/pen_natural.jpeg
6,1,Art was having a party. He realized he didn't ...,Related,3,images/oldmagazines_natural.jpeg
7,2,Art was having a party. He realized he didn't ...,Afforded,3,images/floppydisks_natural.jpeg
8,3,Art was having a party. He realized he didn't ...,Non-Afforded,3,images/pencils_natural.jpeg
9,1,Mike was freezing in the wind. He needed somet...,Afforded,4,images/newspaper_natural.jpeg
10,2,Mike was freezing in the wind. He needed somet...,Non-Afforded,4,images/matchbook_natural.jpeg
11,3,Mike was freezing in the wind. He needed somet...,Related,4,images/skimask_natural.jpeg
12,1,"David was playing hide and seek with his son, ...",Non-Afforded,5,images/cookiejar_natural.jpeg
13,2,"David was playing hide and seek with his son, ...",Related,5,images/broomcloset_natural.jpeg
14,3,"David was playing hide and seek with his son, ...",Afforded,5,images/clothesdryer_natural.jpeg
15,1,Bill was painting his barn. Part of the wall w...,Related,6,images/chair_natural.jpeg
16,2,Bill was painting his barn. Part of the wall w...,Afforded,6,images/tractor_natural.jpeg
17,3,Bill was painting his barn. Part of the wall w...,Non-Afforded,6,images/hammer_natural.jpeg
18,1,Phil was trying to get a barbecue going. He tr...,Afforded,7,images/map_natural.jpeg
19,2,Phil was trying to get a barbecue going. He tr...,Non-Afforded,7,images/rock_natural.jpeg
20,3,Phil was trying to get a barbecue going. He tr...,Related,7,images/bellows_natural.jpeg
21,1,Peggy was babysitting her infant nephew. He wa...,Non-Afforded,8,images/largerefrigerator_natural.jpeg
22,2,Peggy was babysitting her infant nephew. He wa...,Related,8,images/redbeanbag_natural.jpeg
23,3,Peggy was babysitting her infant nephew. He wa...,Afforded,8,images/plasticspoon_natural.jpeg
24,1,Joe's roommates had taken all of the space in ...,Related,9,images/doorknob_natural.jpeg
25,2,Joe's roommates had taken all of the space in ...,Afforded,9,images/vacuumcleaner_natural.jpeg
26,3,Joe's roommates had taken all of the space in ...,Non-Afforded,9,images/electricoutlet_natural.jpeg
27,1,"Jonathan opened up his car's trunk, but the ic...",Afforded,10,images/seveniron_natural.jpeg
28,2,"Jonathan opened up his car's trunk, but the ic...",Non-Afforded,10,images/hamsandwich_natural.jpeg
29,3,"Jonathan opened up his car's trunk, but the ic...",Related,10,images/screwdriver_natural.jpeg
30,1,"After taking a shower at the gym, Sarah discov...",Non-Afforded,11,images/hairpin_natural.jpeg
31,2,"After taking a shower at the gym, Sarah discov...",Related,11,images/hairdryer_natural.jpeg
32,3,"After taking a shower at the gym, Sarah discov...",Afforded,11,images/warmthermos_natural.jpeg
33,1,"At work, Aaron realized that he forgot his cap...",Related,12,images/showercap_natural.jpeg
34,2,"At work, Aaron realized that he forgot his cap...",Afforded,12,images/sandwichwrapper_natural.jpeg
35,3,"At work, Aaron realized that he forgot his cap...",Non-Afforded,12,images/hamburgerbun_natural.png
36,1,Marissa forgot to bring her pillow on her camp...,Afforded,13,images/leaves_natural.jpeg
37,2,Marissa forgot to bring her pillow on her camp...,Non-Afforded,13,images/water_natural.jpeg
38,3,Marissa forgot to bring her pillow on her camp...,Related,13,images/clothes_natural.jpeg
39,1,"After wading barefoot in the lake, Erik needed...",Non-Afforded,14,images/glasses_natural.jpeg
40,2,"After wading barefoot in the lake, Erik needed...",Related,14,images/towel_natural.jpeg
41,3,"After wading barefoot in the lake, Erik needed...",Afforded,14,images/shirt_natural.jpeg
42,1,"While taking a walk, Colleen ran into an old f...",Related,15,images/notepad_natural.jpeg
43,2,"While taking a walk, Colleen ran into an old f...",Afforded,15,images/popsiclestick_natural.jpeg
44,3,"While taking a walk, Colleen ran into an old f...",Non-Afforded,15,images/bentearring_natural.jpeg
45,1,Harry accidentally dropped his book behind his...,Afforded,16,images/rolledpaper_natural.jpeg
46,2,Harry accidentally dropped his book behind his...,Non-Afforded,16,images/smellysock_natural.jpeg
47,3,Harry accidentally dropped his book behind his...,Related,16,images/mophandle_natural.jpeg
48,1,Janet was teaching and needed to draw on the b...,Non-Afforded,17,images/water_natural.jpeg
49,2,Janet was teaching and needed to draw on the b...,Related,17,images/chalk_natural.jpeg
50,3,Janet was teaching and needed to draw on the b...,Afforded,17,images/rice_natural.jpeg
51,1,Judy was using the Xerox machine in the hallwa...,Related,18,images/heroffice_natural.jpeg
52,2,Judy was using the Xerox machine in the hallwa...,Afforded,18,images/thelavatory_natural.jpeg
53,3,Judy was using the Xerox machine in the hallwa...,Non-Afforded,18,images/hermailbox_natural.jpeg

In [14]:
latin_df.to_csv("latin_square_natural.csv", index = False, sep='\t')

In [34]:
df_long = pd.melt(df[['scenario', 'group_id', 'afforded_image', 'non-afforded_image', 'related_image']],
        id_vars=["scenario", "group_id"],
                  var_name="Condition", value_name="image_path")
df_long['Condition'] = df_long['Condition'].apply(lambda x: x.split("_")[0].title())
df_long['image_path'] = df_long['image_path'].apply(lambda x: "images/" + x)
df_long.head(3)

,scenario,group_id,Condition,image_path
0,Brad was sitting in his office when an intrude...,1,Afforded,images/laptopcomputer_natural.jpeg
1,Jenny was hiking in the woods. She left her fr...,2,Afforded,images/pen_natural.jpeg
2,Art was having a party. He realized he didn't ...,3,Afforded,images/floppydisks_natural.jpeg

In [35]:
df_merged = pd.merge(latin_df, df_long)

In [36]:
df_merged

,list_id,scenario,condition,group_id,image_path,Condition
0,1,Brad was sitting in his office when an intrude...,Afforded,1,images/laptopcomputer_natural.jpeg,Afforded
1,2,Brad was sitting in his office when an intrude...,Non-Afforded,1,images/papernapkin_natural.jpeg,Non-Afforded
2,3,Brad was sitting in his office when an intrude...,Related,1,images/huntingrifle_natural.jpeg,Related
3,1,Jenny was hiking in the woods. She left her fr...,Non-Afforded,2,images/nickel_natural.jpeg,Non-Afforded
4,2,Jenny was hiking in the woods. She left her fr...,Related,2,images/string_natural.jpeg,Related
5,3,Jenny was hiking in the woods. She left her fr...,Afforded,2,images/pen_natural.jpeg,Afforded
6,1,Art was having a party. He realized he didn't ...,Related,3,images/oldmagazines_natural.jpeg,Related
7,2,Art was having a party. He realized he didn't ...,Afforded,3,images/floppydisks_natural.jpeg,Afforded
8,3,Art was having a party. He realized he didn't ...,Non-Afforded,3,images/pencils_natural.jpeg,Non-Afforded
9,1,Mike was freezing in the wind. He needed somet...,Afforded,4,images/newspaper_natural.jpeg,Afforded
10,2,Mike was freezing in the wind. He needed somet...,Non-Afforded,4,images/matchbook_natural.jpeg,Non-Afforded
11,3,Mike was freezing in the wind. He needed somet...,Related,4,images/skimask_natural.jpeg,Related
12,1,"David was playing hide and seek with his son, ...",Non-Afforded,5,images/cookiejar_natural.jpeg,Non-Afforded
13,2,"David was playing hide and seek with his son, ...",Related,5,images/broomcloset_natural.jpeg,Related
14,3,"David was playing hide and seek with his son, ...",Afforded,5,images/clothesdryer_natural.jpeg,Afforded
15,1,Bill was painting his barn. Part of the wall w...,Related,6,images/chair_natural.jpeg,Related
16,2,Bill was painting his barn. Part of the wall w...,Afforded,6,images/tractor_natural.jpeg,Afforded
17,3,Bill was painting his barn. Part of the wall w...,Non-Afforded,6,images/hammer_natural.jpeg,Non-Afforded
18,1,Phil was trying to get a barbecue going. He tr...,Afforded,7,images/map_natural.jpeg,Afforded
19,2,Phil was trying to get a barbecue going. He tr...,Non-Afforded,7,images/rock_natural.jpeg,Non-Afforded
20,3,Phil was trying to get a barbecue going. He tr...,Related,7,images/bellows_natural.jpeg,Related
21,1,Peggy was babysitting her infant nephew. He wa...,Non-Afforded,8,images/largerefrigerator_natural.jpeg,Non-Afforded
22,2,Peggy was babysitting her infant nephew. He wa...,Related,8,images/redbeanbag_natural.jpeg,Related
23,3,Peggy was babysitting her infant nephew. He wa...,Afforded,8,images/plasticspoon_natural.jpeg,Afforded
24,1,Joe's roommates had taken all of the space in ...,Related,9,images/doorknob_natural.jpeg,Related
25,2,Joe's roommates had taken all of the space in ...,Afforded,9,images/vacuumcleaner_natural.jpeg,Afforded
26,3,Joe's roommates had taken all of the space in ...,Non-Afforded,9,images/electricoutlet_natural.jpeg,Non-Afforded
27,1,"Jonathan opened up his car's trunk, but the ic...",Afforded,10,images/seveniron_natural.jpeg,Afforded
28,2,"Jonathan opened up his car's trunk, but the ic...",Non-Afforded,10,images/hamsandwich_natural.jpeg,Non-Afforded
29,3,"Jonathan opened up his car's trunk, but the ic...",Related,10,images/screwdriver_natural.jpeg,Related
30,1,"After taking a shower at the gym, Sarah discov...",Non-Afforded,11,images/hairpin_natural.jpeg,Non-Afforded
31,2,"After taking a shower at the gym, Sarah discov...",Related,11,images/hairdryer_natural.jpeg,Related
32,3,"After taking a shower at the gym, Sarah discov...",Afforded,11,images/warmthermos_natural.jpeg,Afforded
33,1,"At work, Aaron realized that he forgot his cap...",Related,12,images/showercap_natural.jpeg,Related
34,2,"At work, Aaron realized that he forgot his cap...",Afforded,12,images/sandwichwrapper_natural.jpeg,Afforded
35,3,"At work, Aaron realized that he forgot his cap...",Non-Afforded,12,images/hamburgerbun_natural.png,Non-Afforded
36,1,Marissa forgot to bring her pillow on her camp...,Afforded,13,images/leaves_natural.jpeg,Afforded
37,2,Marissa forgot to bring her pillow on her camp...,Non-Afforded,13,images/water_natural.jpeg,Non-Afforded
38,3,Marissa forgot to bring her pillow on her camp...,Related,13,images/clothes_natural.jpeg,Related
39,1,"After wading barefoot in the lake, Erik needed...",Non-Afforded,14,images/glasses_natural.jpeg,Non-Afforded
40,2,"After wading barefoot in the lake, Erik needed...",Related,14,images/towel_natural.jpeg,Related
41,3,"After wading barefoot in the lake, Erik needed...",Afforded,14,images/shirt_natural.jpeg,Afforded
42,1,"While taking a walk, Colleen ran into an old f...",Related,15,images/notepad_natural.jpeg,Related
43,2,"While taking a walk, Colleen ran into an old f...",Afforded,15,images/popsiclestick_natural.jpeg,Afforded
44,3,"While taking a walk, Colleen ran into an old f...",Non-Afforded,15,images/bentearring_natural.jpeg,Non-Afforded
45,1,Harry accidentally dropped his book behind his...,Afforded,16,images/rolledpaper_natural.jpeg,Afforded
46,2,Harry accidentally dropped his book behind his...,Non-Afforded,16,images/smellysock_natural.jpeg,Non-Afforded
47,3,Harry accidentally dropped his book behind his...,Related,16,images/mophandle_natural.jpeg,Related
48,1,Janet was teaching and needed to draw on the b...,Non-Afforded,17,images/water_natural.jpeg,Non-Afforded
49,2,Janet was teaching and needed to draw on the b...,Related,17,images/chalk_natural.jpeg,Related
50,3,Janet was teaching and needed to draw on the b...,Afforded,17,images/rice_natural.jpeg,Afforded
51,1,Judy was using the Xerox machine in the hallwa...,Related,18,images/heroffice_natural.jpeg,Related
52,2,Judy was using the Xerox machine in the hallwa...,Afforded,18,images/thelavatory_natural.jpeg,Afforded
53,3,Judy was using the Xerox machine in the hallwa...,Non-Afforded,18,images/hermailbox_natural.jpeg,Non-Afforded